package state

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/coffee-code-io/coffeeenv/internal/sys"
)

func init() { Register(&envHandler{}) }

// envHandler manages environment variables in a single coffeeenv-owned file,
// ~/.config/coffeeenv/activate.sh, which the user sources from their shell rc.
// It never edits the user's rc directly. Each env state independently upserts
// its own `export` line, so multiple env states converge the same file.
type envHandler struct{}

type envDesired struct {
	Name   string `json:"name"`
	Value  string `json:"value"`
	Target string `json:"target"`
	// Expand: when true the value is written with double quotes so shell
	// references like $PATH expand when the file is sourced (used for PATH
	// prepends, e.g. "<dir>/node_modules/.bin:$PATH"). Default single-quoted
	// literal.
	Expand bool `json:"expand"`
}

// envVar is a managed variable's stored value plus its quoting mode.
type envVar struct {
	Value  string
	Expand bool
}

// file returns the managed activate-file path for this env var: the explicit
// target, or the global default.
func (d *envDesired) file() string {
	if d.Target != "" {
		return sys.ExpandPath(d.Target)
	}
	return activatePath()
}

// envObserved is the current state of this var in the managed file.
type envObserved struct {
	Present bool
	Value   string
	Expand  bool
}

func (envHandler) Type() string { return "env" }

func (envHandler) Decode(rs RawState) (Desired, error) {
	var p envDesired
	if err := decodeParams(rs, &p); err != nil {
		return nil, err
	}
	if p.Name == "" {
		return nil, errors.New("env: name is required")
	}
	return &p, nil
}

func (envHandler) Read(_ context.Context, desired Desired) (Observed, error) {
	d := desired.(*envDesired)
	vars, err := readActivate(d.file())
	if err != nil {
		return nil, err
	}
	v, ok := vars[d.Name]
	return &envObserved{Present: ok, Value: v.Value, Expand: v.Expand}, nil
}

func (envHandler) Diff(desired Desired, observed Observed) ([]Action, error) {
	d := desired.(*envDesired)
	o := observed.(*envObserved)
	if o.Present && o.Value == d.Value && o.Expand == d.Expand {
		return nil, nil
	}
	verb := "set"
	if o.Present {
		verb = "update"
	}
	return []Action{{
		StateName: d.Name,
		Kind:      "set-env",
		Summary:   fmt.Sprintf("%s %s=%s in %s", verb, d.Name, d.Value, displayPath(d.file())),
		Payload:   *d,
	}}, nil
}

func (envHandler) Apply(_ context.Context, a Action) error {
	d := a.Payload.(envDesired)
	vars, err := readActivate(d.file())
	if err != nil {
		return err
	}
	vars[d.Name] = envVar{Value: d.Value, Expand: d.Expand}
	return writeActivate(d.file(), vars)
}

// --- managed activate.sh helpers ---

const activateHeader = "# Generated by coffeeenv — do not edit. Source this from your shell rc."

func activatePath() string {
	if dir := os.Getenv("XDG_CONFIG_HOME"); dir != "" {
		return filepath.Join(dir, "coffeeenv", "activate.sh")
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "coffeeenv", "activate.sh")
}

// displayPath shortens a home-relative path to ~/… for readable plan output.
func displayPath(p string) string {
	if home, err := os.UserHomeDir(); err == nil {
		if rel, err := filepath.Rel(home, p); err == nil && !strings.HasPrefix(rel, "..") {
			return "~/" + rel
		}
	}
	return p
}

func readActivate(path string) (map[string]envVar, error) {
	vars := map[string]envVar{}
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return vars, nil
		}
		return nil, err
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		rest, ok := strings.CutPrefix(line, "export ")
		if !ok {
			continue
		}
		name, val, ok := strings.Cut(rest, "=")
		if !ok {
			continue
		}
		value, expand := unquoteShell(strings.TrimSpace(val))
		vars[strings.TrimSpace(name)] = envVar{Value: value, Expand: expand}
	}
	return vars, sc.Err()
}

func writeActivate(path string, vars map[string]envVar) error {
	names := make([]string, 0, len(vars))
	for n := range vars {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString(activateHeader + "\n")
	for _, n := range names {
		fmt.Fprintf(&b, "export %s=%s\n", n, quoteShell(vars[n]))
	}
	return sys.WriteFileAtomic(path, []byte(b.String()), 0o644)
}

// quoteShell renders a value for the activate file. Expand vars use double
// quotes so $-references expand when sourced; others use single-quoted literals.
func quoteShell(v envVar) string {
	if v.Expand {
		// Only escape backslash and double-quote; leave $ live for expansion.
		s := strings.ReplaceAll(v.Value, `\`, `\\`)
		s = strings.ReplaceAll(s, `"`, `\"`)
		return `"` + s + `"`
	}
	return "'" + strings.ReplaceAll(v.Value, "'", `'\''`) + "'"
}

// unquoteShell recovers a value and whether it was double-quoted (expandable).
func unquoteShell(s string) (string, bool) {
	if len(s) >= 2 && s[0] == '\'' && s[len(s)-1] == '\'' {
		inner := s[1 : len(s)-1]
		return strings.ReplaceAll(inner, `'\''`, "'"), false
	}
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		inner := s[1 : len(s)-1]
		inner = strings.ReplaceAll(inner, `\"`, `"`)
		inner = strings.ReplaceAll(inner, `\\`, `\`)
		return inner, true
	}
	return s, false
}
